# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-30 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goclubdb', '0010_auto_20160424_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='province',
            field=models.CharField(blank=True, max_length=52, null=True, verbose_name=b'Province or state'),
        ),
    ]
